Update vector_font.h
have to remove  static const otherwise there is a conflict with FLASH_STR

libs/graphics/vector_font.h:18:28: error: vectorFontPolys causes a section type conflict with flash_X
 static const unsigned char vectorFontPolys[] IN_FLASH_MEMORY = {
                            ^
In file included from libs/graphics/graphics.h:18:0,
                 from libs/graphics/graphics.c:15:
/Volumes/ESPTools/Espruino/1v85/master.new/src/jsutils.h:233:16: note: 'flash_X' was declared here
      FLASH_STR(flash_X, __STRING(X)); \
                ^
/Volumes/ESPTools/Espruino/1v85/master.new/src/jsutils.h:52:40: note: in definition of macro 'FLASH_STR'
 #define FLASH_STR(name, x) static char name[] IN_FLASH_MEMORY = x
                                        ^
libs/graphics/graphics.c:102:3: note: in expansion of macro 'assert'
   assert(data);
   ^