typescript: disable generation typings for globalThis
As it's already builtin to typescript and conflicts:

> types/main.d.ts:12547:15 - error TS2397: Declaration name conflicts with built-in global identifier 'globalThis'.
>
> 12547 declare const globalThis: any;
>                     ~~~~~~~~~~